theme="polymer"
baseurl = "https://manistein.github.io/blog/"
languageCode = "zh-CN"
title = "Manistein's Blog"
MetaDataFormat = "toml"
paginate = 10 # optional
disqusShortname = "Your Disqus Name" # optional
copyright = "© 2017 All rights reserved"

[params]
  author = "Manistein"
  github = "Manistein"
  zhihu  = "people/wu-yin-jie/activities"